name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: clear build files
        run: |
          rm -rf docs && rm -rf node_modules package-lock.json

      - name: Insall pacakages And Build
        env:
          BASE64_ACCESS_TOKEN: ${{ secrets.BASE64_ACCESS_TOKEN }}
        run: |
          npm install &&
          npm run build

      - name: Check Build Files
        run: |
          ls docs

      - name: Save Build Result
        run: |
          git config --global user.email "luyi985@gmail.com" &&
          git config --global user.name "luyi985" &&
          git branch &&
          git add --all &&
          git status &&
          git commit -m "deploy at $(date)" &&
          git push &&
          echo DONE
